## References for app name and version
app:
  name: "weatherDataAPI"
  version: "1.0.0-SNAPSHOT"
  baseUrl: "/v1/rocketcompanies/*"
  
  
keystore:
  Path: "certs/server-keystore.jks"
  Password: "mulesoft12345"
  keyPassword: "mulesoft12345"
  Alias: "mule-server"